2019-10-21 13:59:50,637 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute']
2019-10-21 13:59:50,641 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'instances']
2019-10-21 13:59:50,668 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'instances', u'list']
2019-10-21 13:59:50,672 DEBUG    root            Running [gcloud.compute.instances.list] with arguments: []
2019-10-21 13:59:50,674 DEBUG    root            (gcloud.compute.instances.list) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 784, in Run
    resources = command_instance.Run(args)
  File "/google-cloud-sdk/lib/surface/compute/instances/list.py", line 41, in Run
    client = holder.client
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/base_classes.py", line 66, in client
    self._client = client_adapter.ClientAdapter(self._api_version)
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 56, in __init__
    self._API_NAME, self._api_version, no_http=no_http)
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 320, in GetClientInstance
    check_response_func=CheckResponseForApiEnablement())
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 157, in _GetClientInstance
    http_client = http_creds.Http(response_encoding=http_creds.ENCODING)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/http.py", line 81, in Http
    allow_account_impersonation=allow_account_impersonation)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 318, in LoadIfEnabled
    return Load(allow_account_impersonation=allow_account_impersonation)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 363, in Load
    cred = _Load(account, scopes, prevent_refresh)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 416, in _Load
    raise NoActiveAccountException()
NoActiveAccountException: You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2019-10-21 13:59:50,677 ERROR    root            (gcloud.compute.instances.list) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
